config/routes.rb
Rails.application.routes.draw do
  resources :password_resets

  resources :documents do
    resources :comments, :except => [:show]
    resources :likes
    resources :pages do
      resources :comments, :except => [:show]
      resources :likes
    end
  end

  resources :pages do
    resources :comments, :except => [:show]
    resources :likes
  end
   
  root "documents#index"

  resources :users, :except => [:index]
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in,:current_user, :except => [:login, :attempt_login, :logout]


  def login
    # login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    if authorized_user
      # mark user as logged in
      if params[:remember_me]
        cookies.permanent[:auth_token] = authorized_user.auth_token
      else
        cookies[:auth_token] = authorized_user.auth_token
      end
      flash[:notice] = "Hello #{authorized_user.name}"
      redirect_to(documents_path)
    else
      flash[:notice] = "Invalid username/password combination."
      redirect_to(:action => 'login')
    end
  end

  def logout
    #mark user as logged out
    cookies.delete(:auth_token)
    redirect_to(:action => "login")
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "User Login" %>

<div class="login">
  <h2 style="margin-left:28%">Please Login or Create a new User </h2>
  <hr>
  <%= form_tag(:action => 'attempt_login', :class => "form-horizontal") do %>
      <table class="table table-bordered">
        <tr>
          <th><%= label_tag(:username) %></th>
          <td><%= text_field_tag(:username) %></td>
        </tr>
        <tr>
          <th><%= label_tag(:password) %></th>
          <td><%= password_field_tag(:password) %></td>
        </tr>
      </table>
            <div style="margin-left:35%">
              <%= check_box_tag :remember_me, 1, params[:remember_me] %>
              <%= label_tag(:remember_me) %>

              <%= link_to "Forgot your password?", new_password_reset_path , :style => "margin-left:7%"%>
            </div>

      <%= submit_tag("Log In",:class => "btn btn-primary",:style=>"margin-left:35%") %>
  
            <%= link_to "Sign Up".html_safe, new_user_path, :class => "btn btn-primary"%>
<% end %>

</div>