config/routes.rb
Rails.application.routes.draw do
  resources :password_resets

  resources :documents do
    resources :comments, :except => [:show]
    resources :likes
    resources :pages do
      resources :comments, :except => [:show]
      resources :likes
    end
  end

  resources :pages do
    resources :comments, :except => [:show]
    resources :likes
  end
   
  root "documents#index"

  resources :users, :except => [:index]
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/document.rb
class Document < ActiveRecord::Base
	
  belongs_to :uploader, :class_name => 'User', :foreign_key => 'uploader_id'
  has_many :pages
  has_many :comments , as: :commentable
  has_many :likes , as: :likable

  mount_uploader :attachment , PdfUploader

  validates :name, presence: true,
                   length: { within: 8..25 }
  validates :attachment, presence: true
  validates :description, length: {maximum: 125}

  after_create :create_related_pages
  before_destroy :delete_document_comments, :delete_document_likes
  after_destroy :remove_folder, :remove_related_pages

  def directory
    "/documents/document #{self.id}"
  end
  
  private

  def create_related_pages
    number_of_page = PDF::Reader.new(self.attachment.current_path).page_count
    (1..number_of_page).each do |index|
      page = Page.new(position: index)
      self.pages << page
    end
  end

  def remove_related_pages
    self.pages.destroy_all
  end

  def remove_folder
    folder_location = File.dirname(self.attachment.current_path)
    FileUtils.rm_rf(folder_location)
  end

  def delete_document_comments
    self.comments.destroy_all
  end

  def delete_document_likes
    self.likes.destroy_all
  end


end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  THUMBNAIL_WIDTH = 100
  THUMBNAIL_HEIGHT= 100

  before_action :confirm_logged_in, :current_user
  after_action :create_thumbnail, only: [:create]

  def index
    @documents = Document.all.paginate(:page => params[:page],:per_page => 10)
  end

  def show
    @document = Document.find(params[:id])
 
  end

  def new
  	@document = Document.new
  end

  def create
  	@document =Document.new(document_params)
    @document.uploader = @current_user
    if @document.save
    	flash[:notice] = "The Document #{@document.name} uploaded successfully."
      redirect_to(:action => 'index')
    else
    	render "new"
    end	
  end

  def edit
    @document=Document.find(params[:id])
    unless authorized_user?
      flash[:notice] = "You're not authorized to  edit this document #{@document.name}."
      redirect_to(root_path)
    end
  end

  def update
    @document = Document.find(params[:id])
    if !authorized_user?
      flash[:notice] = "You're not authorized to  update this document #{@document.name}."
      redirect_to(root_path)
    elsif @document.update_attributes(document_params)
      flash[:notice] = "The Document #{@document.name} updated successfully."
      redirect_to(:action => 'index')
    else
      render "edit"
    end
  end

  def destroy
  	@document = Document.find(params[:id])
    unless authorized_user?
      flash[:notice] = "You're not authorized to  delete this document."
      redirect_to(root_path)
    else
      pages = @document.pages
      pages.each do |p|
        p.destroy
      end
      @document.destroy
      flash[:notice] = "The Document #{@document.name} deleted successfully."
      redirect_to request.referrer
    end
  end

  private

  def document_params
  	params.require(:document).permit(:name, :attachment, :description)
  end

  def authorized_user?
    @document.uploader == @current_user
  end

  def create_thumbnail
    thumb = Magick::Image.read(@document.attachment.current_path + "[0]")[0]
    thumb_path = File.dirname(@document.attachment.current_path) + "/thumb.png"
    thumb.write(thumb_path)
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= error_messages_for(@document) %>
<table class="table table-bordered">

  <tr>
    <th><%= f.label :name %></th>
    <td><%= f.text_field :name, :class => "form-control" %></td>
  </tr>
  <% unless is_edit %>
  <tr>
    <th><%= f.label :attachment %></th>
    <td><div class="attachment_field"><%= f.file_field :attachment %></div></td>
  </tr>
      <% end %>
  <tr>
    <th><%= f.label :description %></th>
    <td><%= f.text_area :description ,:class=>"form-control", size: '30x2.5'%></td>
  </tr>

</table>

app/views/documents/delete.html.erb
<% @page_title = "Delete Document" %>

<%= link_to("<< Back to List", documents_path, :class => 'back-link') %>

<div class="document delete">
  <h2>Delete Document</h2>

  <%= form_for(:document, :url => document_path(@document.id),
               :html => {:method => :delete}) do|f| %>

    <p>Are you sure you want to permanently delete this document?</p>

    <p class="reference-name"><%= @document.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Document") %>
    </div>
  <% end %>
</div>

app/views/documents/edit.html.erb
<% @page_title = "Edit Document" %>

<%= link_to("<< Back to List", documents_path, :class => 'back-link') %>

<div class="document edit">
  <h2>Edit Document</h2>

  <%= form_for(@document) do |f| %>

      <%= render(:partial => "form", :locals => {:f => f, is_edit: true}) %>

      <div class="form-buttons">
        <%= submit_tag("Update", :class => "btn btn-default",:style=>"margin-left:50%") %>
      </div>

  <% end %>

</div>

app/views/documents/index.html.erb
<% @page_title = "Documents" %>

<div class="documents index">
  <h2>Documents</h2>
  <hr>

  <%= link_to content_tag(:i,nil,class: 'fa fa-plus fa-lg')+" Add New",
   new_document_path, :class => 'btn btn-primary' %>

  <%= will_paginate @documents %>

  <div><%= pluralize(@documents.size, 'document') %> found</div>
  <table class="table table-bordered" summary="document list">
    <tr class="header">
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Owner</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @documents.each do |document| %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td><%= link_to(image_tag("#{document.directory}/thumb.png", alt: "thumbnail", size: '200x200'), document_pages_path(document_id: document.id),
                          :class => 'action index') %></td>
          <td><%= link_to(document.name, document_pages_path(document_id: document.id), 
                          :class => 'action index') %></td>
          <td><%= link_to(document.uploader.username, user_path(document.uploader.id),
                          :class => 'action show') %></td>
          <td class="center"><%=document.pages.size%></td>
          <td class="actions">
            <%= link_to("Details".html_safe, document_path(id: document.id), :class => 'btn btn-primary') %>
            <br>
            <%= link_to "Download".html_safe, document.attachment_url, class: 'btn btn-primary' %>
            <br>
            <%= link_to("Edit".html_safe, edit_document_path(id: document.id), :class => 'btn btn-primary') if @current_user == document.uploader%>
            <br>
            <%= link_to("Delete".html_safe, document_path(id: document.id), :method => :delete, data: { confirm: "Are you sure you want to delete this document #{document.name}?" }, :class => 'btn btn-danger') if @current_user == document.uploader %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/documents/new.html.erb
<% @page_title = "New Document" %>

<%= link_to("<< Back to List", documents_path, :class => 'back-link') %>

<div class="document new">
  <h2>New Document</h2>

  <%= form_for(@document) do |f| %>

      <%= render(:partial => "form", :locals => {:f => f, is_edit: false}) %>
      <div class="form-buttons">
        <%= submit_tag("Save", :class => "btn btn-primary",:style=>"margin-left:43%")  %>
      </div>

  <% end %>
</div>

app/views/documents/show.html.erb
<% @page_title = "Show Document" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="documents show">
  <h2>Show Document</h2>

  <table class="table table-bordered" summary="Document detail view">
    <tr>
      <th>Name</th>
      <td><%= @document.name %></td>
    </tr>
    <tr>
    <tr>
      <th>Uploader</th>
      <td><%= link_to(@document.uploader.username, user_path(@document.uploader.id)) %></td>
    </tr>
    <tr>
      <th>Pages</th>
      <td><%= @document.pages.size %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @document.description %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @document.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @document.updated_at %></td>
    </tr>
  </table>

</div>